spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: KSA
    url: jdbc:oracle:thin:@10.101.0.201:1521:KSADBUAT
    password: ksa
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10
      connectionTimeout: 30000 #30s
      idleTimeout: 600000 #10 minutes
      maxLifetime: 1800000 #30 minutes
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
